export const FETCH_FILM_DATA_REQUEST = "FETCH_FILM_DATA_REQUEST";
export const FETCH_FILM_DATA_SUCCESS = "FETCH_FILM_DATA_SUCCESS";
export const FETCH_FILM_DATA_FAILURE = "FETCH_FILM_DATA_FAILURE";

export const FETCH_FILM_GENRES_REQUEST = "FETCH_FILM_GENRES_REQUEST";
export const FETCH_FILM_GENRES_SUCCESS = "FETCH_FILM_GENRES_SUCCESS";
export const FETCH_FILM_GENRES_FAILURE = "FETCH_FILM_GENRES_FAILURE";
